spring.application.name=donotlate_project

server.port=80

#Spring DevTools (ìë ë¦¬ë¡ë, ìë² ì¬ìì) ì¤ì )
spring.devtools.livereload.enabled=true

#ì½ë ë³ê²½ ì ìë² ìë ì¬ìì
spring.devtools.restart.enabled=true

#íìë¦¬í ìºì ë¹íì±í (HTML íì¼ ìì  ì ë°ë¡ ë³ê²½ì¬í­ íì¸í  ì ìëë¡)
spring.thymeleaf.cache=false

#ë¡ê·¸ ë ë²¨ ì§ì 
logging.level.com.late.donot=debug

#URL ì ë¬ ë°©ìì ëê³  í­ì ì¿ í¤ë¥¼ íµí´ìë§ ì¸ìì ì ì§
server.servlet.session.tracking-modes=cookie

#기상청 공공 API 서비스 인증키
weather.api.key=85f7bd713b24920967048a843c51a87da661d0b584a054d1640d95517fe7ebfd

#기상청 주간 날씨 API 서비스 인증키
weather.week.api.key=0ab964b59fe3292a6e11dcacab6c171eefbba0b6d705f058711fd6df9c29f835

#카카오 REST API 키
kakao.api.key=4584af7d141d03eb9a1a695d02e4865c

#미세먼지 API 서비스 인증키
dust.api.key=0ab964b59fe3292a6e11dcacab6c171eefbba0b6d705f058711fd6df9c29f835

#자외선 API 서비스 인증키
#ultraviolet.api.key=0ab964b59fe3292a6e11dcacab6c171eefbba0b6d705f058711fd6df9c29f835

#캐시 사용해서 API 호출횟수 줄이기
spring.cache.type=simple

